services:
  db:
    container_name: my_postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: airbnb_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel_network

  pgadmin:
    container_name: my_pgadmin_container
    image: dpage/pgadmin4:9.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root_password
    ports:
      - "8083:80"
    networks:
      - laravel_network

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: YouQuizz
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network: